server:
  port: 8080

spring:
  application:
    name: lab-mybatis
  datasource:
    url: jdbc:mysql://localhost:3306/ssmdemo?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Pp123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml

